### ISSUE TITLE
Embedding locale JSON files

### ISSUE THREAD

**Issue by miolini** [variadico/lctime#1]
Hi!

Thank you for your job! 

lctime.go:101
``` bys, err := ioutil.ReadFile(filepath.Join(localeDir, lc+".json"))```

Does that mean that we should distribute executable binary with a bunch of JSON locale files? Or we have other option?

**Comment by variadico** [comment]
Hey, miolini.

I'm still thinking about the best way to handle this case. I have this documented as a [known issue](https://github.com/variadico/lctime#known-issues) in the readme.

These are some of the solutions I'm thinking about, but feel free to let me know if you think of a better way.

**1. Keep locale data as JSON files.**
Pro: Only locale that is being used will be loaded into memory.
Con: Developers have to distribute locale files with their app.

**2. Use go-bindata to convert data into Go code**
Pro: Locale data will be included in program binary.
Con: Apps would load somewhere around 1MB of locale data into memory.

If we go with approach 1, then people will have to set the locale directory when they import this package. Something like this.

```
lctime.LocaleDir = "./locales"

lctime.SetLocale("es_MX")
lctime.Strftime("%c")
```

Approach number 2, seems easier. Devs won't have to bother users with placing the locales directory in the right place. Right now the locales directory is 1.2MB. If we turn all of the locales into a variable in Go code, I'm not sure how much of a performance impact that'll have on an app. That might affect some people more than others. Maybe. [go-bindata] has compression and a low-memory mode, but I don't know how much memory we could save by doing that.

Any suggestions or feedback are definitely welcome by anyone. I want to think about this a little more before making a decision.

[go-bindata]: https://github.com/jteeuwen/go-bindata

**Comment by variadico** [comment]
After talking with some more people about this, I've decided the small memory overhead is worth avoiding the potential problems with having loose JSON files.

`lctime` will use go-bindata to generate an `internal/locale` package. This means that neither developers nor users will have to worry about locale files and everything will Just Work™.

If you want to set a locale, then just call `lctime.SetLocale` and don't worry about distributing anything extra.

**Comment by miolini** [comment]
Thank you!
