### ISSUE TITLE
Incorrect short-day format for Kiswahili

### ISSUE THREAD

**Issue by joelmukuthu** [variadico/lctime#2]
The short days [here](https://github.com/variadico/lctime/blob/9f7f8bc1df4c6cd38317620ac1bb0bc7757e1196/internal/locales/sw_KE.json#L12-L19) are incorrect, they should be the same as the long days since Kiswahili doesn't have a short format for the week days

**Comment by chubin** [comment]
@variadico We use your perfect library in our project (wttr.in), and one of our users ( @joelmukuthu ) have noted, that the Kiswahili is not correct (not perfect). He has contacted me and recommended to fix the translation. Though it is possible in our local installation, I think, it would be better to do it directly in the upstream (at least we should discuss it here, I think).

What @joelmukuthu recommends to use the following abbreviations instead:

https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/sw-KE/ca-gregorian.json#L125-L132

**Comment by variadico** [comment]
Hello!

Thank you guys for reporting this issue. You guys are awesome. 🍻 

I just opened #3, which hopefully fixes the error. Can you guys verify the changes?

**Comment by chubin** [comment]
Thank you very much @variadico 
It looks good to me. Let's see what @joelmukuthu says.

**Comment by joelmukuthu** [comment]
Thank you @variadico! Looks good to me as well.
